


[workspace]
members = [
    "main_canister",
    "user_canister",
    "file_server_lib"
]


[profile.release]
lto = true
opt-level = 'z'          
codegen-units = 1 
split-debuginfo= "packed"
strip = "debuginfo"
debug = false



