[package]
name = "file_server_canister"
version = "0.1.0"
edition = "2021"
author = "Levi Feldman <levifeldman37@gmail.com>"



[lib]
crate-type = ["cdylib"]


[dependencies]
ic-cdk = "0.7.4"
candid = "0.8.4"
serde = "1.0.137"
serde_bytes = "0.11.6"
base64 = "0.13.0"
sha2 = "0.9.1"



